name: Emacs Package CI (Eask)

on:
  push:
    paths-ignore: ['LICENSE*', '**.md', '**.org']

  pull_request:
    paths-ignore: ['LICENSE*', '**.md', '**.org']

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version: [26.3, 27.2, 28.2, 29.4, 30.2, snapshot]

    steps:
    - name: Check out the source code
      uses: actions/checkout@v5

    - name: Install Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - name: Install Eask
      uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - name: Run tests
      run: |
        eask package
        eask install
        eask compile
